name: docker ngPost-rar

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: debian-latest

    steps:
    - uses: actions/checkout@v3
    - name: ngPost-rar
      run: docker build . --file ngPost-rar --docker-ngpost-rar:$(date +%s)
